
#include <quan/gx/wxwidgets/from_wxString.hpp>
#include <quan/gx/wxwidgets/to_wxString.hpp>
#include <quan/uav/osd/detail/writable_bitmap.hpp>
#include <quan/fs/strip_file_extension.hpp>
#include <quan/fs/get_basename.hpp>
#include <fstream>
#include "../../document.hpp"
#include "../../osd_bmp_app.hpp"
#include "../panel.hpp"
#include "../main_frame.hpp"
#include <wx/choicdlg.h>

using quan::gx::wxwidgets::from_wxString;
using quan::gx::wxwidgets::to_wxString;

void main_frame::OnCreateStaticBitmapFile(wxCommandEvent & event)
{
   wxArrayString choices = wxGetApp().get_panel()->get_bitmap_names();
   
   wxMultiChoiceDialog dlg{
      this
      ,wxT("Choose bitmaps")
      ,wxT("Bitmaps to C+ sources/headers")
      ,choices
   };
   // retrieve last file dir and name from config
   if (dlg.ShowModal() == wxID_OK){

      wxString output_cpp_dir = wxGetApp().get_config()->Read(wxT("/BitmapFont/OutputCppDir"),wxT(""));
      wxString output_cpp_basename = wxGetApp().get_config()->Read(wxT("/Bitmaps/OutputCppFile"),wxT("bitmaps.cpp"));

      wxFileDialog fd {
         wxGetApp().get_main_frame(),
         wxT ("Save Bitmap C++ source file"),
         output_cpp_dir ,// default dir
         output_cpp_basename,                  // default file
         wxT ("C++ source (*.cpp)|*.cpp"), // wildcard
         wxFD_SAVE | wxFD_OVERWRITE_PROMPT
      };

      if (fd.ShowModal() == wxID_CANCEL) {
         return ;
      }
  
      std::string const cpp_filename = from_wxString<char>(fd.GetPath());
      std::string const basename_cpp = quan::fs::get_basename (cpp_filename);
      std::string const no_ext_basename = quan::fs::strip_file_extension(basename_cpp);
      std::string const cpp_file_dir = cpp_filename.substr(0,cpp_filename.rfind('/'));

      wxGetApp().get_config()->Write(wxT("/BitmapFont/OutputCppDir"),to_wxString(cpp_file_dir));
      wxGetApp().get_config()->Write(wxT("/Bitmaps/OutputCppFile"),to_wxString(basename_cpp));

      // check result ok
      std::ofstream out (cpp_filename);

      out << "\n//Generated by OSDMaker for the Quantracker Air OSD\n";
      out << "//https://github.com/kwikius/quantracker\n";
      out << "//https://github.com/kwikius/osd_maker\n\n";
      out << "#include <quan/uav/osd/api.hpp>\n";
      out << "#include <quan/uav/osd/basic_bitmap.hpp>\n\n";
      out << "namespace {\n\n";

      wxArrayInt result = dlg.GetSelections();
      for ( size_t i = 0; i < result.GetCount();++i){
         wxString bmp_name = choices[result[i]];
         // get the bitmap of that name
         typedef quan::uav::osd::dynamic::bitmap dynamic_bitmap;
         dynamic_bitmap* bmp = wxGetApp().get_document()->get_bitmap(
            from_wxString<char>(bmp_name)
         );
         if ( bmp ){
            std::string bmp_name1 = from_wxString<char>(bmp_name);
            bmp->output_header( bmp_name1 + "_type", bmp_name1,out);
         }
      } 

      out << " constexpr quan::uav::osd::bitmap_ptr bitmap_array[] =\n";
      out << "   {\n";
      for ( size_t i = 0; i < result.GetCount();++i){
         std::string bmp_name = from_wxString<char>(choices[result[i]]);
         out << "    ";
         if ( i != 0){
            out << ",";
         }
         out << "&" << bmp_name  <<'\n';
      }
      out << "   };\n} // namespace\n\n";
      out << "quan::uav::osd::bitmap_ptr\n";
      out << "quan::uav::osd::get_bitmap(uint32_t id)\n";
      out << "{\n";
      out << "constexpr uint32_t size = sizeof(bitmap_array)/sizeof(quan::uav::osd::bitmap_ptr);\n";
      out << "  if ( id < size){\n";
      out << "     return bitmap_array[id];\n";
      out << "  }else{\n";
      out << "     return nullptr;\n";
      out << "  }\n";
      out << "}\n";

      out.close();

      // --- source done
 
      wxString output_hpp_dir = wxGetApp().get_config()->Read(wxT("/BitmapFont/OutputHppDir"),wxT(""));
      wxString output_hpp_basename =wxGetApp().get_config()->Read(wxT("/Bitmaps/OutputHppFile"),wxT(""));

      if (output_hpp_dir == wxT("")){
         output_hpp_dir = output_cpp_dir;
      }

      if ( output_hpp_basename == wxT("")){
         output_hpp_basename = to_wxString(no_ext_basename + ".hpp");
      }
      
      wxFileDialog fd1 {
         wxGetApp().get_main_frame(),
         wxT ("Save Bitmap C++ Header file"),
         output_hpp_dir,    // default dir
         output_hpp_basename,   // default file
         wxT ("C++ header (*.hpp)|*.hpp"), // wildcard add *.h
         wxFD_SAVE | wxFD_OVERWRITE_PROMPT
      };

      if (fd1.ShowModal() == wxID_CANCEL) {
         //output warning that ids may be invalid if not done together
         return ;
      }
      
      std::string const hpp_filename = from_wxString<char>(fd1.GetPath());
      std::string const basename_hpp = quan::fs::get_basename (hpp_filename);
      std::string const no_ext_hpp_basename = quan::fs::strip_file_extension(basename_hpp);
      std::string const hpp_file_dir = hpp_filename.substr(0,cpp_filename.rfind('/'));

      output_hpp_dir = to_wxString(hpp_file_dir);
      output_hpp_basename = to_wxString(basename_hpp);
      
      std::ofstream out1 (hpp_filename);
      // check valid
      std::string ubase_name;
      for (auto c: no_ext_hpp_basename){
         char ch1 = ::toupper(c);
         if ( isspace(ch1)){
            ch1 = '_';
         }
         ubase_name += ch1 ;
      }
      time_t timer;
      time(&timer);
   
      // TODO create a unique include guard
      out1 << "#ifndef QUANTRACKER_USER_BITMAP_" << ubase_name << "_" << timer << "_HPP_INCLUDED\n";
      out1 << "#define QUANTRACKER_USER_BITMAP_" << ubase_name << "_" << timer << "_HPP_INCLUDED\n";
      out1 << "//Generated by OSDMaker for the Quantracker Air OSD\n\n";
      out1 << "//https://github.com/kwikius/quantracker\n";
      out1 << "//https://github.com/kwikius/osd_maker\n";
      out1 << "#include <quan/uav/osd/basic_bitmap.hpp>\n\n";
      out1 <<  "   struct BitmapID{\n";

      for ( size_t i = 0; i < result.GetCount();++i){
         std::string bmp_name = from_wxString<char>(choices[result[i]]);
         out1 << "      static constexpr uint32_t " << bmp_name << " = " << i << ";\n";
      }
      out1 << "   };\n";
      out1 << "\n";
      out1 << "#endif // QUANTRACKER_USER_BITMAP_" << ubase_name << "_" << timer <<  "_HPP_INCLUDED\n";

      wxGetApp().get_config()->Write(wxT("/BitmapFont/OutputHppDir"),output_hpp_dir);
      wxGetApp().get_config()->Write(wxT("/Bitmaps/OutputHppFile"),output_hpp_basename);
   }
}



