

#include <ctime>
#include <cstring>
#include <fstream>

#include <quan/fs/strip_file_extension.hpp>
#include <quan/fs/get_basename.hpp>
#include <quan/gx/wxwidgets/from_wxString.hpp>
#include <quan/gx/wxwidgets/to_wxString.hpp>
#include <quan/uav/osd/detail/writable_bitmap.hpp>

#include "../../document.hpp"
#include "../../osd_bmp_app.hpp"
#include "../panel.hpp"
#include "../main_frame.hpp"
#include <wx/choicdlg.h>

using quan::gx::wxwidgets::from_wxString;
using quan::gx::wxwidgets::to_wxString;

void main_frame::OnCreateStaticFontFile(wxCommandEvent & event)
{
   wxArrayString choices = wxGetApp().get_panel()->get_font_names();
   
   wxMultiChoiceDialog dlg{
      this
      ,wxT("Choose fonts")
      ,wxT("Fonts to header")
      ,choices
   };
   if (dlg.ShowModal() == wxID_OK){

       wxFileDialog fd {wxGetApp().get_main_frame(),
         wxT ("Save OSD C++ Font source files"),
         wxT (""),                    // default dir
         wxT (""),                    // default file
         wxT ("C++ source (*.cpp)|*.cpp"), // wildcard
         wxFD_SAVE | wxFD_OVERWRITE_PROMPT
      };
      if (fd.ShowModal() == wxID_CANCEL) {
         return ;
      }
      std::string src_filename = from_wxString<char>(fd.GetPath());
      wxArrayInt result = dlg.GetSelections();
      // check result ok
      std::ofstream out (src_filename);

      out << "\n//Generated by OSDMaker for the Quantracker Air OSD\n";
      out << "//https://github.com/kwikius/quantracker\n";
      out << "//https://github.com/kwikius/osd_maker\n";
      out << "#include <quan/uav/osd/api.hpp>\n";
      out << "#include <quan/uav/osd/basic_bitmap.hpp>\n";
      out << "#include <quan/uav/osd/basic_font.hpp>\n\n";
      out << "namespace {\n\n";

      // check out ok
      for ( size_t i = 0; i < result.GetCount();++i){
         std::string fnt_name = from_wxString<char>(choices[result[i]]);
         // get the font of that name
         typedef quan::uav::osd::dynamic::font dynamic_font;
         dynamic_font* fnt 
            = wxGetApp().get_document()->get_font(fnt_name);
         if ( fnt ){
            db_font const * dbf = dynamic_cast<db_font const *>(fnt);
            if ( dbf){
               dbf->output_header( fnt_name + "_type", fnt_name,out);
            }
         }
      } 

      out << "\n constexpr quan::uav::osd::font_ptr font_array[] =\n";
      out << "   {\n";
      for ( size_t i = 0; i < result.GetCount();++i){
         std::string font_name = from_wxString<char>(choices[result[i]]);
         out << "    ";
         if ( i != 0){
            out << ",";
         }
         out << "&font_" << font_name  <<'\n';
      }
      out << "   };\n} // namespace\n\n";
      out << "quan::uav::osd::font_ptr\n";
      out << "quan::uav::osd::get_font(uint32_t id)\n";
      out << "{\n";
      out << "   constexpr uint32_t size = sizeof(font_array)/sizeof(quan::uav::osd::font_ptr);\n";
      out << "   if ( id < size){\n";
      out << "      return font_array[id];\n";
      out << "   }else{\n";
      out << "      return nullptr;\n";
      out << "   }\n";
      out << "}\n";

      out.close();

      std::string no_ext_filename = quan::fs::strip_file_extension(src_filename);
      
      std::ofstream out1 (no_ext_filename + ".hpp");
      std::string basename = quan::fs::get_basename (no_ext_filename);

      std::string ubase_name;
      for (auto c: basename){
         char ch1 = ::toupper(c);
         if ( isspace(ch1)){
            ch1 = '_';
         }
         ubase_name += ch1 ;
      }
   
      time_t timer;
      time(&timer);

      out1 << "#ifndef QUANTRACKER_USER_FONT_" << ubase_name << "_" << timer <<  "_HPP_INCLUDED\n";
      out1 << "#define QUANTRACKER_USER_FONT_" << ubase_name <<  "_" << timer <<  "_HPP_INCLUDED\n\n";

      out1 << "\n//Generated by OSDMaker for the Quantracker Air OSD\n";
      out1 << "//https://github.com/kwikius/quantracker\n";
      out1 << "//https://github.com/kwikius/osd_maker\n";
      out1 << "#include <quan/uav/osd/basic_font.hpp>\n\n";
      out1 <<  "   struct FontID{\n";

      for ( size_t i = 0; i < result.GetCount();++i){
         std::string fnt_name = from_wxString<char>(choices[result[i]]);
         out1 << "      static constexpr uint32_t " << fnt_name << " = " << i << ";\n";
      }
      out1 << "};\n";
      out1  << "\n";
      out1 << "#endif // QUANTRACKER_USER_FONT_" << ubase_name << "_" << timer <<  "_HPP_INCLUDED\n";
     
   }
}
